# Initialized `ndice.py` generated by ipm.
# Documents at https://ipm.hydroroll.team/

from infini.register import Register
from infini.router import Command
from infini.input import Input
from infini.output import Output
from diceutils.utils import format_str
from diceutils.dicer import Dicer


register = Register()
register.register_textevent(
    "ndice.roll",
    "[{{ card_name }}]"
    "{% if reason %}由于[{{ reason }}]{% endif %}掷骰: "
    "{% if descs|length == 1 %}"
    "{{ descs[0] }}"
    "{% else %}"
    "{{ db }}=[...]="
    "{% for outcome in outcomes %}"
    "{{ outcome }}"
    "{% if not loop.last %}, {% endif %}"
    "{% endfor %}"
    "{% endif %}",
)
register.register_textevent(
    "ndice.error.bad_roll_string",
    "[{{ card_name }}]掷骰时出现异常, 疑似掷骰表达式错误.",
)
register.register_textevent(
    "ndice.error.too_much_round", "[{{card_name }}]给入的掷骰轮数超出预期."
)
register.register_textevent(
    "ndice.error.unknown",
    "未知错误: {{ error }}, 可能是掷骰语法异常.\nBUG提交: https://gitee.com/unvisitor/issues",
)
register.register_textevent(
    "ndice.error.bad_round", "[{{ card_name }}]多轮检定的轮数应当是整型数."
)
register.register_textevent(
    "ndice.error.too_much_round", "[{{ card_name }}]多轮检定的轮数超出预期."
)


def roll(input: Input, args: str, name: str = None) -> str:
    time = 1
    if "#" in args:
        args = args.split("#")

        try:
            time = int(args[0].strip())
            if time > 20:
                return Output(
                    "text", "ndice.error.too_much_round", variables={"username": name}
                )
        except ValueError:
            return Output("text", "ndice.error.bad_round", variables={"username": name})

        if len(args) == 1:
            args = "1d100"
        else:
            args = args[1]
    else:
        args = args.strip()

    args = args.split()
    if len(args) > 1:
        reason = args[1]
    else:
        reason = None

    roll_string = args[0]
    descs = []
    outcomes = []

    try:
        dice = Dicer(roll_string).roll()
        descs.append(dice.description())
        outcomes.append(dice.outcome)

        for _ in range(time - 1):
            dice.roll()
            descs.append(dice.description())
            outcomes.append(dice.outcome)
    except ValueError:
        return input.output(
            "text",
            "ndice.error.bad_roll_string",
            status=1,
        )

    return input.output(
        "text",
        "ndice.roll",
        variables={
            "username": name,
            "descs": descs,
            "outcomes": outcomes,
            "db": dice.db,
            "reason": reason,
        },
    )


@register.handler(Command("r", alias="roll"), priority=3)
def roll_handler(input: Input):
    args = format_str(input.get_plain_text(), begin=(".r", ".roll"))

    if not args:
        return roll(input, "1d100")

    try:
        return roll(input, args)
    except Exception as error:
        return input.output(
            "text", "ndice.error.unknown", variables={"error": str(error)}
        )
